FROM golang:1.22-alpine

# Install air for hot reload
RUN go install github.com/cosmtrek/air@v1.49.0

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

# Run air for hot reload
CMD ["air", "-c", ".air.toml"]